command: |
  bs launch application -n "DRAGEN RNA" --app-version {version}
  -o app-session-name:"DRAGEN-RNA_{version}_{run_name}"
  -o ht-ref:custom
  -o ht-id:34866044255
  -o project-id:{project_id}
  -o enable-quantification:true
  -o gene-annotations:34849714824
  -o enable-gene-fusion:true
  -o enable-variant-calling:true
  -o enable-annotation:true
  -o annotation-genome:GRCh38
  -o basespace-labs-disclaimer:Accepted
  -o commandline-disclaimer:true
  -o coverage_list.coverage_bed_id:34851417089
  -o coverage_list.tag:gencode.v44
  -o sample-id:biosamples/{biosamples}